# Generated by Django 2.2 on 2020-01-19 15:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200119_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': '开发人员', 'verbose_name_plural': '开发人员'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '测试任务', 'verbose_name_plural': '测试任务'},
        ),
        migrations.AlterModelOptions(
            name='progress1',
            options={'verbose_name': '需求理解进度(%)', 'verbose_name_plural': '需求理解进度(%)'},
        ),
        migrations.AlterModelOptions(
            name='progress2',
            options={'verbose_name': '测试用例编写进度(%)', 'verbose_name_plural': '测试用例编写进度(%)'},
        ),
        migrations.AlterModelOptions(
            name='progress3',
            options={'verbose_name': '测试用例执行进度(%)', 'verbose_name_plural': '测试用例执行进度(%)'},
        ),
        migrations.AlterModelOptions(
            name='progress4',
            options={'verbose_name': '测试报告编写进度(%)', 'verbose_name_plural': '测试报告编写进度(%)'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.AlterModelOptions(
            name='subsystem',
            options={'verbose_name': '子系统', 'verbose_name_plural': '子系统'},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '所属团队', 'verbose_name_plural': '所属团队'},
        ),
        migrations.AlterModelOptions(
            name='tester',
            options={'verbose_name': '测试人员', 'verbose_name_plural': '测试人员'},
        ),
        migrations.AddField(
            model_name='item',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 19, 15, 20, 55, 142664, tzinfo=utc), verbose_name='上线日期'),
        ),
        migrations.AlterField(
            model_name='item',
            name='developer',
            field=models.ManyToManyField(to='polls.Developer', verbose_name='开发人员'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sub_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.SubSystem', verbose_name='子系统'),
        ),
        migrations.AlterField(
            model_name='item',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.System', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='item',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Team', verbose_name='所属团队'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tester',
            field=models.ManyToManyField(to='polls.Tester', verbose_name='测试人员'),
        ),
    ]
