# Generated by Django 2.2 on 2020-01-20 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200119_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 20, 12, 34, 23, 928675, tzinfo=utc), verbose_name='上线日期'),
        ),
    ]
