# Generated by Django 2.2 on 2020-03-06 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200203_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='存在的风险')),
                ('pub_date', models.DateField(default=datetime.datetime(2020, 3, 6, 15, 26, 18, 82842, tzinfo=utc), verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '协调事项',
                'verbose_name_plural': '协调事项',
            },
        ),
        migrations.CreateModel(
            name='OtherWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='其他')),
                ('pub_date', models.DateField(default=datetime.datetime(2020, 3, 6, 15, 26, 18, 81841, tzinfo=utc), verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '其他工作',
                'verbose_name_plural': '其他工作',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='存在的风险')),
                ('pub_date', models.DateField(default=datetime.datetime(2020, 3, 6, 15, 26, 18, 82842, tzinfo=utc), verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '存在的风险',
                'verbose_name_plural': '存在的风险',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='完成情况'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 6, 15, 26, 18, 64826, tzinfo=utc), verbose_name='上线日期'),
        ),
        migrations.AlterField(
            model_name='progress1',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 6, 15, 26, 18, 80841, tzinfo=utc), verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='progress2',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 6, 15, 26, 18, 80841, tzinfo=utc), verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='progress3',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 6, 15, 26, 18, 81841, tzinfo=utc), verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='progress4',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 6, 15, 26, 18, 81841, tzinfo=utc), verbose_name='更新日期'),
        ),
    ]
