# Generated by Django 2.2 on 2020-03-07 01:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20200307_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matter',
            name='team',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='team',
        ),
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 7, 1, 39, 9, 517311, tzinfo=utc), verbose_name='上线日期'),
        ),
        migrations.AlterField(
            model_name='matter',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 1, 39, 9, 537330, tzinfo=utc), verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='otherwork',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 1, 39, 9, 537330, tzinfo=utc), verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='progress1',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 1, 39, 9, 535329, tzinfo=utc), verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='progress2',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 1, 39, 9, 536330, tzinfo=utc), verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='progress3',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 1, 39, 9, 536330, tzinfo=utc), verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='progress4',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 1, 39, 9, 537330, tzinfo=utc), verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 1, 39, 9, 537330, tzinfo=utc), verbose_name='更新日期'),
        ),
    ]
