# Generated by Django 2.2 on 2020-03-07 03:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20200307_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 7, 3, 43, 33, 257640, tzinfo=utc), verbose_name='上线日期'),
        ),
        migrations.AlterField(
            model_name='matter',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 3, 43, 33, 276657, tzinfo=utc), verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='otherwork',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 3, 43, 33, 275655, tzinfo=utc), verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='progress1',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 3, 43, 33, 274654, tzinfo=utc), verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='progress2',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 3, 43, 33, 274654, tzinfo=utc), verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='progress3',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 3, 43, 33, 274654, tzinfo=utc), verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='progress4',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 3, 43, 33, 275655, tzinfo=utc), verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 3, 43, 33, 275655, tzinfo=utc), verbose_name='更新日期'),
        ),
    ]
